### ISSUE TITLE
lume throw uncontroller error if install is empty

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/lume#27]
```yml
install:
  run: 
```

```
Traceback (most recent call last):
  File "/Users/*/miniconda3/envs/pytocho/bin/lume", line 8, in <module>
    sys.exit(main())
  File "/Users/*/miniconda3/envs/pytocho/lib/python3.6/site-packages/lume/src/application/cli/lume.py", line 49, in main
    config = get_config(filename=config_file).unwrap_or_else(
  File "/Users/*/miniconda3/envs/pytocho/lib/python3.6/site-packages/lume/src/application/cli/lume.py", line 31, in get_config
    config = Config(lume_dict)
  File "/Users/*/miniconda3/envs/pytocho/lib/python3.6/site-packages/lume/config/config.py", line 21, in __init__
    self.install = InstallConfig.from_dict(yaml_dict.get("install"))
  File "/Users/*/miniconda3/envs/pytocho/lib/python3.6/site-packages/lume/config/install_config.py", line 13, in from_dict
    run = check_list_or_str_item(kdict, "run", required=True)
  File "/Users/*/miniconda3/envs/pytocho/lib/python3.6/site-packages/lume/config/check_list_or_str_item.py", line 4, in check_list_or_str_item
    raise TypeError(f"StepConfig must contains {key}{suffix} variable")
TypeError: StepConfig must contains run variable
```

Maybe, it requires a better error explanation.

**Comment by fgsalomon** [comment]
Sí, yo creo que si es posible debería indicar el nombre del step y distinguir si falta el `run` o si está vacío.
