### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [alice-biometrics/lume#32]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.13. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary lume -w /tmp/ext lume==0.2.13
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting lume==0.2.13
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/7be/e603f72fe81ac/lume-0.2.13.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-5q3yb2dv/lume/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-5q3yb2dv/lume/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-5q3yb2dv/lume/pip-egg-info
         cwd: /tmp/pip-wheel-5q3yb2dv/lume/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-5q3yb2dv/lume/setup.py", line 14, in <module>
        with open("requirements/requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by acostapazo** [comment]
Reproduced in:

https://github.com/alice-biometrics/lume/pull/33/checks?check_run_id=695511647

**Comment by acostapazo** [comment]
[New version](https://github.com/alice-biometrics/lume/releases/tag/v0.2.14) should solve this issue.

@thatch thanks for your feedback 👍
